// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPITrail;

#nullable disable

namespace WebAPITrail.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230719125830_creat")]
    partial class creat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPITrail.Course", b =>
                {
                    b.Property<string>("courseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("courseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("departments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("courseId");

                    b.ToTable("courses");
                });

            modelBuilder.Entity("WebAPITrail.Learns", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("courseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("semester")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.Property<float?>("grade")
                        .HasColumnType("real");

                    b.HasKey("StudentId", "courseId", "semester", "year");

                    b.HasIndex("courseId");

                    b.ToTable("Learns");
                });

            modelBuilder.Entity("WebAPITrail.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("level")
                        .HasColumnType("int");

                    b.HasKey("StudentId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("WebAPITrail.Learns", b =>
                {
                    b.HasOne("WebAPITrail.Student", "student")
                        .WithMany("learn")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPITrail.Course", "course")
                        .WithMany("learn")
                        .HasForeignKey("courseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("course");

                    b.Navigation("student");
                });

            modelBuilder.Entity("WebAPITrail.Course", b =>
                {
                    b.Navigation("learn");
                });

            modelBuilder.Entity("WebAPITrail.Student", b =>
                {
                    b.Navigation("learn");
                });
#pragma warning restore 612, 618
        }
    }
}
